version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      - conda env update --name ${READTHEDOCS_VERSION} --file environment_dev_update.yml
      - conda list

conda:
  environment: environment.yml

sphinx:
  fail_on_warning: true

# Build PDF
formats:
  - pdf
