version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      - conda list

conda:
  environment: environment_dev.yml

sphinx:
  fail_on_warning: true

# Build PDF (ePuB causes "duplicated ToC entry found" between html pages and the epub xhtml pages)
formats:
  - pdf
