version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_install:
      - mamba env update -f docs/environment_addition_r_rtd.yml
      - Rscript docs/install_github_r_deps.R
      - conda list

conda:
  environment: environment_dev.yml

#sphinx:
#  fail_on_warning: true
