version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_install:
      - mamba env update -f environment_addition_r_rtd.yml
      - Rscript -e 'devtools::install_github("chrisschuerz/SWATdata")'
      - Rscript -e 'devtools::install_github("chrisschuerz/SWATrunR")'
      - conda list

conda:
  environment: environment_dev.yml

#sphinx:
#  fail_on_warning: true
