version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_install:
      - conda list

conda:
  environment: environment_dev.yml

#sphinx:
#  fail_on_warning: true
