name: boa
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
  - pytest
  - myst-nb
  - jupyter
  - pip
  - pip:
    # we use external role, which is from v4.4. in conda this causes conflicts
    - pytest-cov
    - invoke
    - isort
    - flake8
    - flakeheaven>=3.0.0
    - black==22.6.0
    - sphinx>=4.4
    - pydata-sphinx-theme
    - sphinxext-remoteliteralinclude
