name: boa
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
  - black<=22.3.0
  - black[jupyter]
  - isort
  - flake8
  - flakeheaven>=3.0.0
  - pytest
  - invoke
  - sphinx
  - myst-nb
  - pydata-sphinx-theme
  - jupyter
  - pip
  - pip:
    - sphinxext-remoteliteralinclude