name: boa
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
  - myst-nb
  - jupyter
  - pip
  - pip:
    # we use external role, which is from v4.4. in conda this causes conflicts
    - pytest
    - pytest-cov
    - invoke
    - isort
    - flake8
    - flakeheaven>=3.0.0
    - black==22.6.0
    - sphinx>=4.4,<6  # <6 b/c pydata (<=0.12) doesn't work with sphinx 6, 4.4 is when certain sphinx options were introduced that we use
    - pydata-sphinx-theme<0.12.0  # pydata 0.12 has a flyout menu bug
    - sphinxext-remoteliteralinclude
