name: boa
channels:
- pytorch
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.9
- mkl<2022
- pytorch<1.12.0
- torchvision
- torchaudio
- numpy
  # 2022/09/25 Pinning because pandas 1.4.3 broke something with ax
  # ax is working on a fix
- pandas<=1.4.0
- xarray
- dask
- netCDF4
- bottleneck
- scipy
- scikit-learn
- click
- sqlalchemy
- pip
- pip:
  - ax-platform
  - PyYAML
  - -e .
