name: boa
channels:
- pytorch
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.9
- pytorch-nightly::pytorch
- pytorch-nightly::torchvision
- pytorch-nightly::torchaudio
- numpy
- pandas
- xarray
- dask
- netCDF4
- bottleneck
- scipy
- scikit-learn
- click
- sqlalchemy
- pip
- pip:
  - ax-platform>=0.2.8
  - PyYAML
  - -e .
