name: boa
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
  - invoke
  - isort
  - pytest
  - myst-nb
  - jupyter
  - flake8
  - flakeheaven>=3.0.0
  - black
  - pip
  - pip:
    # we use external role, which is from v4.4. in conda this causes conflicts
    - sphinx>=4.4
    - pydata-sphinx-theme
    - sphinxext-remoteliteralinclude
