name: boa
channels:
#- pytorch-nightly
- pytorch
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.9
- mkl<2022
- pytorch<1.12.0
- torchvision
- torchaudio
- numpy
- pandas
- scipy
- scikit-learn
- click
- sqlalchemy
- plotly
- notebook
- ipywidgets
- ax-platform
- PyYAML
- pip
- pip:
  - -e . --install-option="--no-deps"
