name: boa
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
  - black
  - isort
  - flake8
  - flakeheaven>=3.0.0
  - pytest
  - invoke
  - myst-nb
  - jupyter
  - pip
  - pip:
    - sphinx
    - pydata-sphinx-theme
    - black[jupyter]
    - sphinxext-remoteliteralinclude