name: optiwrap-dev
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.10
- click
- jupyter
- numpy
- pandas
- sphinx
- sqlalchemy
- xarray
- flake8
- invoke
- pip
- pip:
  - PyYAML
  - ax-platform
  - black
  - black[jupyter]
  - conda-merge
  - isort
  - myst-nb
  - pydata-sphinx-theme
  - pytest
  - torch
  - torchaudio
  - torchvision
  - flakeheaven
  - -e .
