name: optiwrap-dev
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.9
- numpy
- pandas
- sphinx
- xarray
- dask
- netCDF4
- bottleneck
- invoke
- jupyter
- click
- sqlalchemy
- flake8
- pip
- pip:
  - torch
  - torchaudio
  - torchvision
  - PyYAML
  - ax-platform
  - isort
  - pytest
  - black
  - black[jupyter]
  - pydata-sphinx-theme
  - myst-nb
  - flakeheaven
  - -e .
