name: boa
channels:
- pytorch
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.9
- mkl<2022
- pytorch<1.12.0
- torchvision
- torchaudio
- numpy
- pandas
- xarray
- dask
- netCDF4
- bottleneck
- scipy
- scikit-learn
- click
- sqlalchemy
- pip
- pip:
  - ax-platform
  - PyYAML
  - -e .
