name: optiwrap
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.10
- numpy
- pandas
- xarray
- click
- sqlalchemy
- pip
- pip:
  - torch
  - torchvision
  - torchaudio
  - ax-platform
  - PyYAML
  - -e .
