name: optiwrap
channels:
- conda-forge
- pytorch
- anaconda
- defaults
dependencies:
- python=3.9
- numpy
- pandas
- xarray
- pytorch
- click
- torchvision
- sqlalchemy
- pip
- pip:
  - PyYAML
  - pytest
  - black
  - isort
