[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 39
skip_glob = ["*env*/*"]

[tool.black]
line-length = 100
preview=true
# These are regular expressions (hence the \. is escaping the ., and not a literal \.)
exclude = '''
(
    /(\.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | .*env.*
    | _build
    | buck-out
    | build
    | dist
    | docs/*
    )
)
'''

[tool.flakeheaven]
# make output nice
format = "grouped"
# 80 chars aren't enough in 21 century
max_line_length = 100
# show line of source code in output
show_source = true
