[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 39
skip_glob = ["*env*/*"]


[tool.black]
line-length = 100
preview=true
# These are regular expressions (hence the \. is escaping the ., and not a literal \.)
include = 'optiwrap'
exclude = '''
(
    /(\.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | .*env.*
    | _build
    | buck-out
    | build
    | dist
    | docs/*
    )/
    | .*\.yaml
    | .*\.yml
    | __pycache__
)
'''
