# Single objective optimization config
optimization_options:
    objective_options:
        objectives:
            - boa_metric: mean
    scheduler:
        total_trials: 15
parameters:
    x0:
        type: range
        bounds: [-5.0, 10.0]
    x1:
        type: range
        bounds: [0.0, 15.0]
# These are all defaults, so we don't need to specify them in this case
#script_options:
#    wrapper_path: ./wrapper.py
#    wrapper_name: Wrapper
#    working_dir: .
#    experiment_dir: ... # this is where boa will write logs to by default
                         # if not specified it will be working_dir/experiment_name
#    append_timestamp: True
# This last option appends a timestamp to our output experiment directory.
# This is also the default (True)
