optimization:
    objective: rmse
    metrics:
        rmse:
            name: rmse
            metric: RMSE
            metric_type: boa
            noise_sd: .1

generation_strategy:
    method: fast
    initialization_budget: 5
orchestrator:
    total_trials: 20

parameters:
    x0:
        'bounds': [ -5, 10 ]
        'type': 'range'
        'parameter_type': 'float'
    x1:
        'bounds': [ 0, 15 ]
        'type': 'range'
        'parameter_type': 'float'

# options only needed by the model and not BOA
# You can put anything here that your model might need
model_options:
    input_size: 15

script_options:
    wrapper_path: ./script_wrappers.py
    wrapper_name: BraninWrapper
    append_timestamp: True
