optimization_options:
  obsfile: '/Users/madelinescyphers/projs/fetch3_nhl/data/sapflux_data.csv'
  obsvar: 'md_oak'
  model_path: '/Users/madelinescyphers/projs/fetch3_nhl'
  data_path: "/Users/madelinescyphers/projs/fetch3_nhl/data"
  working_dir: "/Users/madelinescyphers/projs/optiwrap/output"
  output_fname: 'ds_canopy.nc'
  experiment_name: "fetch_UMBS_test_oak"
  # objective_name: "ssqr"
  objective_name: "mse"
  ntrials: 3
  max_parallelism_cap: 3

model_options:
  ###############################################################################
  #INPUT DATA FILE PARAMETERS
  ###############################################################################

  # File for input met data
  input_fname: "UMBS_flux_2011.csv"

# Start and end in the fetch2 example
  start_time: "2011-07-24 14:00:00" #begining of simulation #DOY 160
  end_time: "2011-07-24 14:30:00" #end #DOY190 - 7/10 is doy 191

  dt:  1800  #seconds - input data resolution
  tmin:  0  #tmin [s]

  ###############################################################################
  #SITE INFORMATION
  ###############################################################################
  latitude:  45.5598  # From AmeriFlux UMBS page
  longitude:  -84.7138
  time_offset:  -5 #Offset from UTC time, e.g EST = UTC -5 hrs

  ###############################################################################
  #RUN OPTIONS - printing
  ###############################################################################
  # Printing slows down model run
  # Options to turn printing off or specify print frequency
  print_run_progress:  True  # Turn on/off printing for progress of time steps calculated
  print_freq:  100  # Interval of timesteps to print if print_run_progress = True (e.g. 1 will print every time step)

  ###############################################################################
  #TRANSPIRATION OPTIONS - NHL OR PM
  ###############################################################################
  transpiration_scheme:  1 # 0: PM transpiration; 1: NHL transpiration
  zenith_method: "CN"  # Method to use for zenith angle calculation (if using NHL)

  ###############################################################################
  #NUMERICAL SOLUTION TIME AND SPACE CONSTANTS (dz and dt0)
  ###############################################################################
  #The finite difference discretization constants
  dt0:  20  #model temporal resolution [s]
  dz:  0.2  #model spatial resolution [m]

  stop_tol:  0.01  #stop tolerance of equation converging

  #############################################################################
  #MODEL PARAMETERS
  #Values according to Verma et al., 2014
  ############################################################################

  #CONFIGURING SOIL BOUNDARY CONDITIONS
  #Here the user can choose the desired contition by setting the numbers as
  #described below

  #The configuration used follows Verma et al. 2014

  #############################################################################

  #Upper Boundary condition

  #1 = no flux (Neuman)
  #0 = infiltration


  #Bottom Boundary condition

  #2 = free drainage
  #1 = no flux (Neuman)
  #0 = constant potential (Dirichlet)

  UpperBC: 0
  BottomBC: 0

  # TREE INFO
  species:  "Oak"

  LAD_norm:  'LAD_data.csv' #LAD data


  ###############################################################################
  # PHYSICAL CONSTANTS
  ###############################################################################
  Rho:  998  ##[kg m-3] kg water/m3sapwood. 998 is in the fetch2 example
  g:  9.81 # [m s-2]

  #######################################################################
  #LEAF AREA DENSITY FORMULATION (LAD) [1/m]
  #######################################################################
  lad_scheme :  1  #0: default scheme, based on Lalic et al 2014; 1: scheme from NHL module

parameters:

  #SOIL SPATIAL DISCRETIZATION

  Root_depth:
    type: fixed
    value: 3.2 #[m] depth of root column
  Soil_depth:
    type: fixed
    value: 5   #[m]depth of soil column

  ####################################################################
  #CONFIGURATION OF SOIL DUPLEX
  #depths of layer/clay interface
  #####################################################################

  sand_d:
    type: fixed
    value: 5.0 #4.2----top soil #m
  clay_d:
    type: fixed
    value: 4.2 #0------4.2 #m

  #SOIL INITIAL CONDITIONS
  #soil initial conditions as described in the paper [VERMA et al., 2014]
  #the initial conditions were constant -6.09 m drom 0-3 metres (from soil bottom)
  #from 3 meters, interpolation of -6.09 m to -0.402 m between 3-4.2 m
  #from 4,2 m [sand layer] cte value of -0.402 m

  cte_clay:
    type: fixed
    value: 3 #depth from 0-3m initial condition of clay [and SWC] is constant
  H_init_soilbottom:
    type: fixed
    value: -6.09
  H_init_soilmid:
    type: fixed
    value: -0.402
  H_init_canopytop:
    type: fixed
    value: -23.3

  #SOIL PARAMETERS - USING VAN GENUCHTEN RELATIONSHIPS
  # Van Genuchten parameters for UMBS from fetch2_example_amf.m

  #CLAY
  alpha_1:
    type: fixed
    value: 0.8                       #soil hydraulic parameter [1/m]
  theta_S1:
    type: fixed
    value: 0.55                     #saturated volumetric soil moisture content [-]
  theta_R1:
    type: fixed
    value: 0.068                    #residual volumetric soil moisture content [-]
  n_1:
    type: fixed
    value: 1.5                           #soil hydraulic parameter  [-]
  #m_1 = 1-(1/n_1)
  m_1:
    type: fixed
    value: 0.33333333333333337            #soil hydraulic parameter  [-]
  Ksat_1:
    type: fixed
    value: 1.94e-7               #saturated hydraulic conductivity  [m/s]

  #SAND
  alpha_2:
    type: fixed
    value: 14.5
  theta_S2:
    type: fixed
    value: 0.47
  theta_R2:
    type: fixed
    value: 0.045
  n_2:
    type: fixed
    value: 2.4
  ##m_2 = 1-(1/n_2)
  m_2:
    type: fixed
    value: 0.5833333333333333
  Ksat_2:
    type: fixed
    value: 3.45e-5

  #Soil stress parameters
  theta_1_clay:
    type: fixed
    value: 0.08
  theta_2_clay:
    type: fixed
    value: 0.12

  theta_1_sand:
    type: fixed
    value: 0.05
  theta_2_sand:
    type: fixed
    value: 0.09



  #ROOT PARAMETERS
  #diving by Rho*g since Richards equation is being solved in terms of \Phi (Pa)
  #Kr divided by rho*g
  Kr:
    type: fixed
    value: 7.346938775510204e-14 #soil-to-root radial conductance [m/sPa]
  qz:
    type: fixed
    value: 9
  #Ksax divided by rho*g                                       #unitless - parameter for the root mass distribution - Verma et al., 2014
  Ksax:
    type: fixed
    value: 1.0204081632653063e-09   #specific axial conductivity of roots  [ m/s]
  Aind_r:
    type: fixed
    value: 1                                       #m2 root xylem/m2 ground]

  #XYLEM PARAMETERS
  #kmax divided by rho*g
  kmax:
    type: fixed
    value: 1.0204081632653063e-09   #conductivity of xylem  [ m2/sPa]
  ap:
    type: fixed
    value: 2.0e-6                                  #xylem cavitation parameter [Pa-1]
  bp:
    type: fixed
    value: -1.5e+6                                #xylem cavitation parameter [Pa]
  Aind_x:
    type: fixed
    value: 8.62e-4                           #m2 xylem/m2 ground]
  Phi_0:
    type: fixed
    value: 5.74e+8                               #From bohrer et al 2005
  p:
    type: fixed
    value: 20                                          #From bohrer et al 2005
  sat_xylem:
    type: range
    bounds: [0.4, 0.7]
    # type: fixed
    # value: 0.573                                  #From bohrer et al 2005
  sapwood_area:
    type: fixed
    value: 0.0177
  theta_sat_x:
    type: fixed
    value: 573 # Pa
  taper_top:
    type: fixed
    value: 0.2

  #TREE PARAMETERS
  Hspec: # From 2011 Tree info in FETCH2 Matlab example
    type: fixed
    value: 22.0                      #Height average of trees [m]
  LAI:
    type: fixed
    value: 37.8507360000000                        #[-] Leaf area index
  Abasal:
    type: fixed
    value: 8.62e-4         #[m2basal/m2-ground] xylem cross-sectional area and site surface ratio

  #########################################################################3
  #NHL PARAMETERS
  ###########################################################################

  scale_nhl:
    type: range
    bounds: [0.1, 2.0]

  mean_crown_area_sp: #[m2]
  # From 2011 Tree info in FETCH2 Matlab example
    type: fixed
    value: 26.8600000000000
  total_crown_area_sp: #[m2]
  # From 2011 Tree info in FETCH2 Matlab example
    type: fixed
    value: 2171.75744784689
  plot_area:
    # From 2011 Tree info in FETCH2 Matlab example
    type: fixed
    value: 75649.5511
  sum_LAI_plot:
    type: fixed
    value: 3.7850736000000005

  Cd:
    type: fixed
    value: 0.2 # Drag coefficient
  alpha_ml:
    type: fixed
    value: 0.1  # Mixing length constant
  Cf:
    type: fixed
    value: 0.85  #Clumping fraction [unitless], assumed to be 0.85 (Forseth & Norman 1993) unless otherwise specified
  x:
    type: fixed
    value: 6.67330000000000  #Ratio of horizontal to vertical projections of leaves (leaf angle distribution), assumed spherical (x=1)

  Vcmax25:
    type: fixed
    value: 59.9300000000000
  alpha_gs:
    type: fixed
    value: 6.67330000000000
  alpha_p:
    type: fixed
    value: 1

  wp_s50:
    type: fixed
    value: -9.1e+5 #value for oak from Mirfenderesgi
  c3:
    type: fixed
    value: 12.3 #value for oak from Mirfenderesgi





  #parameters if using penman-monteith transpiration scheme, based on Lalic et al 2014
  #if using NHL transpiration scheme, LAD is calculated in NHL module
  L_m:
    type: fixed
    value: 0.4  #maximum value of LAD a canopy layer
  z_m:
    type: fixed
    value: 11   #height in which L_m is found [m]

  ###########################################################################
  #PENMAN-MONTEITH EQUATION PARAMETERS
  ###########################################################################
  #W m^-2 is the same as J s^-1 m^-2
  #1J= 1 kg m2/s2
  #therefore 1W/m2 = kg/s3

  gb:
    type: fixed
    value: 2.0e-2          #m/s Leaf boundary layer conductance
  Cp:
    type: fixed
    value: 1200                # J/m3 K Heat capacity of air
  ga:
    type: fixed
    value: 2.0e-2          #m/s Aerodynamic conductance
  lamb:
    type: fixed
    value: 2.51e+9        #J/m3 latent heat of vaporization
  gama:
    type: fixed
    value: 66.7              #Pa/K psychrometric constant

  #########################################################################3
  #JARVIS PARAMETERS
  ###########################################################################

  gsmax:
    type: fixed
    value: 10.0e-3      #m/s Maximum leaf stomatal conductance
  kr:
    type: fixed
    value: 5.0e-3         #m2/W Jarvis radiation parameter
  kt:
    type: fixed
    value: 1.6e-3       #K-2  Jarvis temperature parameter
  Topt:
    type: fixed
    value: 289.15           #K   Jarvis temperature parameter (optimum temperature)
  kd:
    type: fixed
    value: 1.1e-3       #Pa-1 Jarvis vapor pressure deficit temperature
  hx50:
    type: fixed
    value: -1274000         #Pa  Jarvis leaf water potential parameter
  nl:
    type: fixed
    value: 2                   #[-] Jarvis leaf water potential parameter
  Emax:
    type: fixed
    value: 1.0e-9        #m/s maximum nightime transpiration