name: ci-win

on:
  push:
    branches:
      - 'develop'
      - 'main'

  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\boa

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          # windows has a problem where sometimes if conda installs a version of a package
          # but pip needs a higher version of that package (because of dependencies)
          # an OSError can happen because of access issues.
          # If that happens in the future, you can move that conda package to pip,
          # Or pin it to a higher version
          python-version: 3.9
          activate-environment: boa
          environment-file: environment_dev.yaml

      - name: Lint
        shell: pwsh
        run: |
          invoke lint
          invoke black --checkonly
          invoke isort --checkonly

      - name: Run tests
        shell: pwsh
        run: pytest -s